home_not_alone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('secret_santa.urls'), name='home'),
    path('invitations/', include('invitations.urls', namespace='invitations')),
]

secret_santa/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.EventList.as_view(), name="home"),
    path("add_event/", views.add_event, name="add_event"),
    path("delete_event/<int:event_id>/", views.delete_event, name="delete_event"),
    path("edit_event/<int:edit_id>/", views.edit_event, name="edit_event"),
    path("view_event/<int:event_id>/", views.view_event, name="view_event"),
    path("edit_participant/<int:event_id>/", views.edit_participant, name="edit_participant"),
    path("random_santa/<int:event_id>/", views.random_santa, name="random_santa"),
    path("invite_participant/<int:participant_id>/", views.invite_participant, name="invite_participant"),    
]

secret_santa/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from decimal import Decimal

CURRENCY = ((0, "€"), (1, "£"), (2, "$"))

class Event(models.Model):
    """
    Stores information about the event
    """
   
    organiser = models.ForeignKey(User, on_delete=models.CASCADE, related_name='events')
    title = models.CharField(max_length=50)
    description = models.TextField(max_length=200, null=True, blank=True)
    currency = models.IntegerField(choices=CURRENCY, default=0, blank=True)
    budget = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    event_image = CloudinaryField('image', default='placeholder', blank=True)
    event_date = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Participant(models.Model):
    """
    Represents an individual participating in a Secret Santa event.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='participant_profile', null=True, blank=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='participants')
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=254, unique=False, null=True, blank=True)
    wishlist = models.TextField(blank=True, null=True)
    assigned_recipient = models.ForeignKey(
        'self', 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True, 
        related_name='gifter'
    )

    def __str__(self):
        return f"{self.name} ({self.event.title})"

secret_santa/forms.py
from cloudinary.forms import CloudinaryFileField
from django import forms
from django.core.exceptions import ValidationError
from .models import Event, Participant


class EventForm(forms.ModelForm):
    """
    Form for adding or editing an events.
    """
    class Meta:
        """
        **Model**: :model:`Event`

        **Fields**:

        1. ``title``: Text field for entering the item name.
        2. ``description``: TextInput for entering a description.
        3. ``event_image``: File input for uploading an image.
        4. ``currency``: Dropdown field to select the currency.
        5. ``budget``: Decimal to select event budget.

        """
        model = Event
        fields = ['title', 'description', 'event_date', 'event_image', 'currency', 'budget']
        labels = {
            'title': 'Event Title',
            'description': 'Event Description',
            'event_date': 'Event Date',
            'event_image': 'Event Image',
            'currency': 'Select Currency',
            'budget': 'Recomended budget',
        }
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Enter Title'}),
            'description': forms.TextInput(
                attrs={'placeholder': 'Enter Description'}
            ),
            'event_date': forms.DateInput(attrs={'type': 'date',}),
            'budget': forms.NumberInput(attrs={'placeholder': '0.00',}),
            
        }

class ParticipantForm(forms.ModelForm):
    """
    Form for adding or editing a participant.
    """
    class Meta:
        model = Participant
        fields = ['name', 'email']  # Include the email field here
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Enter Name'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Enter Email'}),
        }

class ParticipantWishlistForm(forms.ModelForm):
    """
    Form for particapant to update wishlist.
    """
    class Meta:
        model = Participant
        fields = ['wishlist']
        widgets = {
            'wishlist': forms.Textarea(attrs={'placeholder': 'Enter your wishlist items...'})
        }

secret_santa/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator
from django.urls import reverse
from django.contrib import messages
from django.http import HttpResponseRedirect
from invitations.utils import get_invitation_model
import random
from .models import Participant, Event
from .forms import EventForm, ParticipantForm, ParticipantWishlistForm

Invitation = get_invitation_model()

# Used to check and display content related to the user with a 'organiser' group designation
def is_organiser(user):
    return user.is_authenticated and user.groups.filter(name='Organiser').exists()

# Used to check and display content related to the user with a 'participant' group designation
def is_participant(user):
    return user.is_authenticated and user.groups.filter(name='Participant').exists()

@method_decorator(login_required, name='dispatch')
class EventList(View):
    """
    Displays the main page differently based on user role:
    - Organiser: Shows event list and option to create and manage events.
    - Participant: Shows participant portal with event details, recipient, and wishlist form.
    """
    template_name = "secret_santa/index.html"

    def get(self, request, *args, **kwargs):
        # Displays either participant portal or organiser content on index page based on user role
        context = self.get_context_data()
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        # Form to update wishlist if logged in as 'participant'
        if is_participant(request.user):
            participant = Participant.objects.get(user=request.user)
            form = ParticipantWishlistForm(request.POST, instance=participant)
            if form.is_valid():
                form.save()
                messages.success(request, "Your wishlist has been updated!")
            return redirect('/')
        return redirect('/')

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = {}

        if is_organiser(user):
            events = Event.objects.filter(organiser=user).order_by("-created_at")
            context['events'] = events
            context['is_organiser'] = True
            context['is_participant'] = False
        elif is_participant(user):
            participant = get_object_or_404(Participant, user=user)
            event = participant.event
            assigned_recipient = participant.assigned_recipient
            form = ParticipantWishlistForm(instance=participant)

            context['is_organiser'] = False
            context['is_participant'] = True
            context['event'] = event
            context['participant'] = participant
            context['assigned_recipient'] = assigned_recipient
            context['form'] = form
        else:
            context['events'] = None
            context['is_organiser'] = False
            context['is_participant'] = False

        return context

@login_required
@user_passes_test(is_organiser, login_url='home')
def add_event(request):
    """
    Allows an organiser to create a new event.
    Checks for valid form submission and saves a new event linked to the organiser.
    """
    if request.method == "POST":
        event_form = EventForm(request.POST, request.FILES)
        if event_form.is_valid():
            event = event_form.save(commit=False)
            event.organiser = request.user
            event.save()
            messages.success(request, "Event added successfully!")
            return redirect("home")
    else:
        event_form = EventForm()

    return render(request, "secret_santa/add_event.html", {"event_form": event_form})

@login_required
def edit_event(request, edit_id):
    """
    Allows an organiser to edit an existing event.
    Redirects back to index page on success.
    """
    event = get_object_or_404(Event, pk=edit_id, organiser=request.user)

    if request.method == "POST":
        event_form = EventForm(request.POST, request.FILES, instance=event)
        if event_form.is_valid():
            event_form.save()
            messages.success(request, "Event Updated!")
            return HttpResponseRedirect(reverse("home"))
        messages.error(request, "Error updating event!")
    else:
        event_form = EventForm(instance=event)

    return render(request, "secret_santa/edit_event.html", {
        "event_form": event_form,
        "edit_id": edit_id,
    })

@login_required
def delete_event(request, event_id):
    """
    Allows an organiser to delete an event.
    On POST confirmation, deletes the event and redirects to home.
    """
    event = get_object_or_404(Event, pk=event_id, organiser=request.user)
    if request.method == "POST":
        event.delete()
        messages.success(request, "Event deleted successfully!")
    return redirect("home")

@login_required
def view_event(request, event_id):
    """
    Allows an organiser to view details 
    of a specific event and added participants.    
    """
    event = get_object_or_404(Event, pk=event_id, organiser=request.user)
    event_form = EventForm(instance=event)
    participants = Participant.objects.filter(event=event)
    is_organiser_flag = request.user.is_authenticated and request.user.groups.filter(name="Organiser").exists()

    return render(request, 'secret_santa/view_event.html', {
        "event": event,
        "participant": participants,
        "is_organiser": is_organiser_flag,
        "event_form": event_form,
    })

@login_required
def edit_participant(request, event_id):
    """
    Allows an organiser to manage participants for an event:
    - Add new participants
    - Edit existing participants' details
    - Delete participants
    """
    event = get_object_or_404(Event, pk=event_id, organiser=request.user)
    participants = Participant.objects.filter(event=event)
    form = ParticipantForm()

    if request.method == 'POST':
        # Opens form to edit existing participant
        if 'edit' in request.POST:
            pk = request.POST.get('edit')
            participant = get_object_or_404(Participant, id=pk, event=event)
            form = ParticipantForm(instance=participant)

        # Update existing participant
        elif 'save' in request.POST:
            pk = request.POST.get('save')
            if pk:
                participant = get_object_or_404(Participant, id=pk, event=event)
                form = ParticipantForm(request.POST, instance=participant)
                if form.is_valid():
                    form.save()
                    messages.success(request, 'Participant edited!')
            else:
                # Create a new participant
                form = ParticipantForm(request.POST)
                if form.is_valid():
                    new_participant = form.save(commit=False)
                    new_participant.event = event
                    new_participant.save()
                    messages.success(request, 'Participant added!')
            form = ParticipantForm()
        # Delete a participant
        elif 'delete' in request.POST:
            pk = request.POST.get('delete')
            if pk:
                participant = get_object_or_404(Participant, id=pk, event=event)
                participant.delete()
                messages.success(request, 'Participant deleted!')
        # Cancel and redirect to view_event page
        elif 'cancel' in request.POST:
            return redirect('edit_participant', event_id=event_id)

    return render(request, 'secret_santa/edit_participant.html', {
        'event': event,
        'participants': participants,
        'form': form,
    })

@login_required
def random_santa(request, event_id):
    """
    Organiser can randomly assign participants to each other.
    Ensures there are enough participants before shuffling and assigning.
    Once assigned, each participant's 'assigned_recipient' field is updated.
    """
    event = get_object_or_404(Event, pk=event_id, organiser=request.user)
    participants = list(Participant.objects.filter(event=event))

    if len(participants) < 2:
        messages.error(request, "Not enough participants to assign recipients.")
        return redirect('view_event', event_id=event.id)

    random.shuffle(participants)

    for i in range(len(participants)):
        santa = participants[i]
        recipient = participants[(i + 1) % len(participants)]
        santa.assigned_recipient = recipient
        santa.save()

    messages.success(request, "Recipients assigned successfully!")
    return redirect('view_event', event_id=event.id)

def is_organiser(user):
    return user.is_authenticated and user.groups.filter(name='Organiser').exists()

@login_required
@user_passes_test(is_organiser, login_url='home')
def invite_participant(request, participant_id):
    """
    Allows an organiser to send an invitation email to a participant who does not yet have a user account.
    Sends an invite link to the participant's email address.
    """
    participant = get_object_or_404(Participant, id=participant_id, event__organiser=request.user)
    if participant.email:
        try:
            invitation = Invitation.create(email=participant.email, inviter=request.user)
            invitation.send_invitation(request)
            messages.success(request, f"Invitation link sent to {participant.email}!")
        except Exception as e:
            messages.error(request, f"Failed to send invitation to {participant.email}. An email has already been sent")
    else:
        messages.error(request, "Participant has no email specified.")

    return redirect('view_event', event_id=participant.event.id)

def is_participant(user):
    return user.is_authenticated and user.groups.filter(name='Participant').exists()

@login_required

secret_santa/templates/secret_santa/add_event.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Add Event{% endblock %}

{% block content %}
<section class="container container-v-center">

    <h2 class="header-white">Add Event</h2>

    <!-- Form to create a new event -->
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <!-- Display the form fields with crispy layout -->
        {{ event_form | crispy }}

        <!-- Submit button for adding a new event -->
        <button type="submit" class="btn--orange px-4">Add Event</button>

        <!-- Cancel button to navigate back to the home page -->
        <a href="{% url 'home' %}" class="btn btn--gray">Cancel</a>
    </form>
</section>
{% endblock %}

secret_santa/templates/secret_santa/assign_santa.html
<div class="row justify-content-center contributor-container brand-dark rounded">
    <div class="col-12 mt-2 text-center">
        <h3 class="header-white">Santa assigned<span> </h3>
    </div>
    <div class="mt-4">
        <form action="{% url 'random_santa' event.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary" {% if event.participants.all|length == 0 or event.participants.all.0.assigned_recipient %}disabled{% endif %}>Assign Secret Santa</button>
          </form>
        {% if event.participants.all.0.assigned_recipient %}
        <h4>Secret Santa Pairs:</h4>
        <ul class="container--white text--black">
            {% for participant in event.participants.all %}
            <li>{{ participant.name }} is Santa for {{ participant.assigned_recipient.name }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>

secret_santa/templates/secret_santa/edit_event.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Edit Event{% endblock %}

{% block content %}
<section class="container container-v-center">

    <h2 class="header-white">Edit Event</h2>

    <!-- Form for editing the expense space -->
    <form method="post" action="{% url 'edit_event' edit_id=edit_id %}" enctype="multipart/form-data">
        {% csrf_token %}

        <!-- Display the form fields using Crispy Forms -->
        {{ event_form | crispy }}

        <!-- Save and Cancel -->
        <button type="submit" class="btn--orange px-4">Save</button>
        <a href="{% url 'home' %}" class="btn btn--gray">Cancel</a>
    </form>
</section>

<script>

    //Script to hide 'image currently' field and disable currency field

    const pageUrl = window.location.href;

    if (pageUrl.includes('edit_event')) {
        const currencyField = document.getElementById('id_currency');
        const imageContainer = document.getElementById('div_id_space_image');
        const imageCurrentField = imageContainer.querySelector('div');

        if (imageCurrentField) {
            imageCurrentField.setAttribute('hidden', true);
        }

        if (currencyField) {
            currencyField.classList.add('readonly');
        }
    }
</script>


{% endblock %}

secret_santa/templates/secret_santa/edit_participant.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<section class="mx-auto my-3 container-v-center">
    <h2 class="header-white">Participants</h2>

    <div class="p-2 my-3 container--white box-shadow rounded">
        <table class="table">
            <caption class="visually-hidden">List of participants with edit and delete actions</caption>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th class="text-end">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for p in participants %}
                {% if form.instance.id == p.id %}
                {% include 'secret_santa/save_participant.html' %}
                {% else %}
                <tr>
                    <td>{{ p.name }}</td>
                    <td>{{ p.email }}</td>
                    <td class="text-end">
                        <form method="post" action="{% url 'edit_participant' event.id %}" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" name="edit" value="{{ p.id }}" class="btn btn-link edit-icon"
                                title="Edit Participant">
                                <i class="fa-regular fa-pen-to-square"></i>
                            </button>
                        </form>

                        <form method="post" action="{% url 'edit_participant' event.id %}" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" name="delete" value="{{ p.id }}" class="btn btn-link p-0 delete-icon"
                                title="Remove Participant">
                                <i class="fa-solid fa-x"></i>
                            </button>
                        </form>
                    </td>
                </tr>
                {% endif %}
                {% empty %}
                <tr>
                    <td colspan="3">No participants added</td>
                </tr>
                {% endfor %}

                {% if not form.instance.id %}
                <tr>
                    <td colspan="3">
                        <form method="post" action="{% url 'edit_participant' event.id %}">
                            {% csrf_token %}
                            {{ form.name }}
                            {{ form.email }}
                            <button type="submit" name="save" class="btn btn-link add-icon">
                                <i class="fa-solid fa-plus"></i>
                            </button>
                        </form>
                    </td>
                </tr>
                {% endif %}
            </tbody>
        </table>
    </div>

    <div class="d-flex justify-content-center">
        <a href="{% url 'view_event' event.id %}" class="btn btn--orange mx-auto">Back to Event</a>
    </div>
</section>
{% endblock %}

secret_santa/templates/secret_santa/save_participant.html
<tr>
  <td colspan="2">
    <form method="post" action="{% url 'edit_participant' event.id %}">
      {% csrf_token %}
      {{ form.name }}
      {{ form.email }}
      <button type="submit" name="save" value="{{ form.instance.id }}" class="btn btn-link save-icon"
        title="Save Changes">
        <i class="fa-solid fa-check"></i>
      </button>
      <button type="submit" name="cancel" value="{{ form.instance.id }}" class="btn btn-link cancel-icon"
        title="Cancel Changes">
        <i class="fa-solid fa-ban"></i>
      </button>      
    </form>
  </td>
</tr>

secret_santa/templates/secret_santa/view_event.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% if user.is_authenticated %}
<section class="container mt-4">

    <div class="row justify-content-center mb-3">
        <div class="col-12">
            <h1 class="header-white text-center">{{ event.title }}</h1>
        </div>
        <div class="col-12 text-center">
            {% if "placeholder" in event.event_image.url %}
            <img src="{% static 'images/placeholder.webp' %}" class="event-image" alt="placeholder image">
            {% else %}
            <img src="{{ event.event_image.url }}" class="event-image" alt="{{ event.title }}">
            {% endif %}
        </div>
        <div class="col-12 text-center">
            {% if event.description %}
            <div class="row">
                <div class="col-12"><p class="view-card-label">{{event_form.description.label}}:</p></div>
                <div class="col-12"><p class="view-card-value">{{ event.description }}</p></div>
            </div>
            {% endif %}
            {% if event.event_date %} 
            <div class="row">
                <div class="col-12"><p class="view-card-label">{{event_form.event_date.label}}:</p></div>
                <div class="col-12"><p class="view-card-value">{{ event.event_date|date:"d M Y" }}</p></div>
            </div>
            {% endif %}
            {% if event.budget %}  
            <div class="row">
                <div class="col-12"><p class="view-card-label">{{event_form.budget.label}}:</p></div>
                <div class="col-12"><p class="view-card-value">{{ event.budget }} {{ event.get_currency_display }}</p></div>
            </div>
            {% endif %}
        </div>
        
        
    </div>

    <!-- Display participants -->
    <div class="row my-4">
        <h2 class="header-white">Participants</h2>
        <table class="table table-striped table-light mt-3">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Gift Recipient</th>
                    <th>Email</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                {% for p in participant %}
                <tr>
                    <td>{{ p.name }}</td>
                    <td>
                        {% if p.assigned_recipient %}
                        {{ p.assigned_recipient.name }}
                        {% else %}
                        Not assigned
                        {% endif %}
                    </td>
                    <td>{{ p.email }}</td>
                    <td>
                        {% if is_organiser and p.email and not p.user %}
                        <a href="{% url 'invite_participant' p.id %}" class="btn btn-sm btn-primary">Send Invitation to
                            {{ p.name }}</a>
                        {% else %}
                        <span>{{ p.name }} has accepted</span>
                        {% endif %}
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4">No participants found.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="d-flex justify-content-between align-items-center">
        <a href="{% url 'edit_participant' event.id %}" class="btn btn--blue">Edit Participants</a>
        <a href="{% url 'random_santa' event.id %}" class="btn btn--orange">Assign Random Santas</a>
    </div>
</section>

{% else %}
<section class="container mt-4">
    <div class="body-content" id="about">
        <h2>Please login to view events.</h2>
    </div>
</section>
{% endif %}
{% endblock %}